/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAgentsRouteImport } from './routes/_authenticated/agents'
import { Route as AuthenticatedAgentsAgentIdRouteImport } from './routes/_authenticated/agents_.$agentId'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as AuthenticatedWorkflowsWorkflowIdRunsRouteImport } from './routes/_authenticated/workflows_.$workflowId.runs'
import { Route as AuthenticatedWorkflowsWorkflowIdEditRouteImport } from './routes/_authenticated/workflows_.$workflowId.edit'
import { Route as AuthenticatedRunsRunIdRouteImport } from './routes/_authenticated/runs_.$runId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsRoute = AuthenticatedAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgentsAgentIdRoute = AuthenticatedAgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowsWorkflowIdRunsRoute = AuthenticatedWorkflowsWorkflowIdRunsRouteImport.update({
  id: '/workflows/$workflowId/runs',
  path: '/workflows/$workflowId/runs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkflowsWorkflowIdEditRoute = AuthenticatedWorkflowsWorkflowIdEditRouteImport.update({
  id: '/workflows/$workflowId/edit',
  path: '/workflows/$workflowId/edit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRunsRunIdRoute = AuthenticatedRunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/workflows/$workflowId/runs': typeof AuthenticatedWorkflowsWorkflowIdRunsRoute
  '/workflows/$workflowId/edit': typeof AuthenticatedWorkflowsWorkflowIdEditRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/agents': typeof AuthenticatedAgentsRoute
  '/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/workflows/$workflowId/runs': typeof AuthenticatedWorkflowsWorkflowIdRunsRoute
  '/workflows/$workflowId/edit': typeof AuthenticatedWorkflowsWorkflowIdEditRoute
  '/runs/$runId': typeof AuthenticatedRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated': typeof AuthenticatedRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/agents': typeof AuthenticatedAgentsRoute
  '/_authenticated/agents/$agentId': typeof AuthenticatedAgentsAgentIdRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRoute
  '/_authenticated/workflows/$workflowId/runs': typeof AuthenticatedWorkflowsWorkflowIdRunsRoute
  '/_authenticated/workflows/$workflowId/edit': typeof AuthenticatedWorkflowsWorkflowIdEditRoute
  '/_authenticated/runs/$runId': typeof AuthenticatedRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/agents'
    | '/agents/$agentId'
    | '/workflows'
    | '/workflows/$workflowId/runs'
    | '/workflows/$workflowId/edit'
    | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/agents'
    | '/agents/$agentId'
    | '/workflows'
    | '/workflows/$workflowId/runs'
    | '/workflows/$workflowId/edit'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/agents'
    | '/_authenticated/agents/$agentId'
    | '/_authenticated/workflows'
    | '/_authenticated/workflows/$workflowId/runs'
    | '/_authenticated/workflows/$workflowId/edit'
    | '/_authenticated/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthenticatedRoute: typeof AuthenticatedRoute
}

export interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAgentsRoute: typeof AuthenticatedAgentsRoute
  AuthenticatedAgentsAgentIdRoute: typeof AuthenticatedAgentsAgentIdRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRoute
  AuthenticatedWorkflowsWorkflowIdRunsRoute: typeof AuthenticatedWorkflowsWorkflowIdRunsRoute
  AuthenticatedWorkflowsWorkflowIdEditRoute: typeof AuthenticatedWorkflowsWorkflowIdEditRoute
  AuthenticatedRunsRunIdRoute: typeof AuthenticatedRunsRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/agents': {
      id: '/_authenticated/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthenticatedAgentsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/agents/$agentId': {
      id: '/_authenticated/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AuthenticatedAgentsAgentIdRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/workflows/$workflowId/runs': {
      id: '/_authenticated/workflows/$workflowId/runs'
      path: '/workflows/$workflowId/runs'
      fullPath: '/workflows/$workflowId/runs'
      preLoaderRoute: typeof AuthenticatedWorkflowsWorkflowIdRunsRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/workflows/$workflowId/edit': {
      id: '/_authenticated/workflows/$workflowId/edit'
      path: '/workflows/$workflowId/edit'
      fullPath: '/workflows/$workflowId/edit'
      preLoaderRoute: typeof AuthenticatedWorkflowsWorkflowIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
    '/_authenticated/runs/$runId': {
      id: '/_authenticated/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof AuthenticatedRunsRunIdRouteImport
      parentRoute: typeof AuthenticatedRouteImport
    }
  }
}

const authenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAgentsRoute: AuthenticatedAgentsRoute,
  AuthenticatedAgentsAgentIdRoute: AuthenticatedAgentsAgentIdRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRoute,
  AuthenticatedWorkflowsWorkflowIdRunsRoute: AuthenticatedWorkflowsWorkflowIdRunsRoute,
  AuthenticatedWorkflowsWorkflowIdEditRoute: AuthenticatedWorkflowsWorkflowIdEditRoute,
  AuthenticatedRunsRunIdRoute: AuthenticatedRunsRunIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(authenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
